driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # https://github.com/chef/bento
  - name: centos-5.11-i386
  - name: centos-5.11
  - name: centos-6.6-i386
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: dflt_w_ym
    run_list:
      - recipe[test::yum_utils]
      - recipe[nginx-repo]
      - recipe[test::install_nginx]
    includes:
      - centos-5.11-i386
      - centos-5.11
      - centos-6.6-i386
      - centos-6.6
      - centos-7.1

  - name: mnln_w_ym
    run_list:
      - recipe[test::yum_utils]
      - recipe[nginx-repo]
      - recipe[test::install_nginx]
    attributes:
      nginx-repo:
        nginx-stable:
          managed: false
        nginx-mainline:
          managed: true
    includes:
      - centos-5.11-i386
      - centos-5.11
      - centos-6.6-i386
      - centos-6.6
      - centos-7.1

  - name: stbl_src_w_ym
    run_list:
      - recipe[test::yum_utils]
      - recipe[nginx-repo]
      - recipe[test::install_nginx_source]
    includes:
      - centos-5.11-i386
      - centos-5.11
      - centos-6.6-i386
      - centos-6.6
      - centos-7.1
    attributes:
      nginx-repo:
        nginx-stable-source:
          managed: true

  - name: mnln_src_w_ym
    run_list:
      - recipe[test::yum_utils]
      - recipe[nginx-repo]
      - recipe[test::install_nginx_source]
    includes:
      - centos-5.11-i386
      - centos-5.11
      - centos-6.6-i386
      - centos-6.6
      - centos-7.1
    attributes:
      nginx-repo:
        nginx-mainline:
          managed: true
        nginx-mainline-source:
          managed: true
